### ISSUE TITLE
Blog Settings are in config files

### ISSUE THREAD

**Issue by charles-smith** [madskristensen/Miniblog.Core#18]
Might be a little easier for some people to use if there was a basic admin page that could modify these settings.

**edit**, looking a bit closer... it's using file storage for the entire blog. Not that it is a bad thing, just not what I was expecting. Probably not worth doing this unless the posts and comments changed too.

**Comment by madskristensen** [comment]
I've purposefully not created an admin for the settings to reduce the amount of code. It may be a good idea to add.

The reason it is using flat XML files is so you can port your existing BlogEngine.NET or Miniblog over to Miniblog.Core because they use the same XML file format. I did create an interface `IBlogService` so that anyone could write a database, blog storage, whatever provider if they don't want XML files

**Comment by charles-smith** [comment]
That's reasonable. Didn't know about BlogEngine.NET. Now that `FileBlogService` is written it'd probably be fairly trivial to make an importer to any db service someone might make... I'll play around with that.
